<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentationRepoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('documentation_repo')->insert([
            ['keyword' => 'Fever', 'template' => 'Patient presented with high fever, possibly due to infection.'],
            ['keyword' => 'Weight Loss', 'template' => 'Patient reports unexplained weight loss over the past few weeks.'],
            ['keyword' => 'Anorexia', 'template' => 'Patient complains of loss of appetite and reduced food intake.'],
            ['keyword' => 'Pruritus', 'template' => 'Patient reports severe itching, possibly related to dermatological or systemic conditions.'],
            ['keyword' => 'Night Sweats', 'template' => 'Patient experiences excessive sweating at night, requiring further investigation.'],
            ['keyword' => 'Fatigue', 'template' => 'Patient complains of persistent fatigue and lack of energy.'],
            ['keyword' => 'Lumps/Swellings', 'template' => 'Patient noticed a lump/swelling in the [specific area], requiring evaluation.'],
            ['keyword' => 'Cough', 'template' => 'Patient has a persistent cough, possibly related to respiratory infection.'],
            ['keyword' => 'Sputum', 'template' => 'Patient reports coughing up sputum, which is [color/consistency].'],
            ['keyword' => 'Haemoptysis', 'template' => 'Patient reports coughing up blood, requiring urgent evaluation.'],
            ['keyword' => 'Dyspnoea', 'template' => 'Patient complains of shortness of breath, especially during [activity].'],
            ['keyword' => 'Wheeze', 'template' => 'Patient reports wheezing, possibly indicative of asthma or COPD.'],
            ['keyword' => 'Chest Pain', 'template' => 'Patient complains of chest pain, described as [sharp/dull/pressure].'],
            ['keyword' => 'Phinonhoea', 'template' => 'Patient reports abnormal breathing sounds, possibly related to respiratory conditions.'],
            ['keyword' => 'Hoarseness', 'template' => 'Patient complains of hoarseness, possibly due to laryngeal issues.'],
            ['keyword' => 'Orthopnoea', 'template' => 'Patient reports difficulty breathing while lying flat.'],
            ['keyword' => 'PND', 'template' => 'Patient experiences paroxysmal nocturnal dyspnoea, requiring further evaluation.'],
            ['keyword' => 'Palpitations', 'template' => 'Patient complains of irregular or rapid heartbeats.'],
            ['keyword' => 'Dizziness', 'template' => 'Patient reports episodes of dizziness, possibly related to cardiovascular or neurological issues.'],
            ['keyword' => 'Blackouts', 'template' => 'Patient experienced a blackout, requiring further investigation.'],
            ['keyword' => 'Ankle Swelling', 'template' => 'Patient reports swelling in the ankles, possibly related to fluid retention.'],
            ['keyword' => 'Pedal Swelling', 'template' => 'Patient reports swelling in the feet, possibly related to fluid retention.'],
            ['keyword' => 'Abdominal Pain', 'template' => 'Patient complains of abdominal pain, localized to [specific area].'],
            ['keyword' => 'Nausea', 'template' => 'Patient reports nausea, possibly related to gastrointestinal issues.'],
            ['keyword' => 'Vomiting', 'template' => 'Patient has been vomiting, described as [color/consistency].'],
            ['keyword' => 'Haematemesis', 'template' => 'Patient reports vomiting blood, requiring urgent evaluation.'],
            ['keyword' => 'Dysphagia', 'template' => 'Patient complains of difficulty swallowing, possibly related to esophageal issues.'],
            ['keyword' => 'Dyspepsia (Indigestion)', 'template' => 'Patient reports indigestion and discomfort after meals.'],
            ['keyword' => 'Diarrhoea', 'template' => 'Patient has been experiencing diarrhea, described as [frequency/consistency].'],
            ['keyword' => 'Constipation', 'template' => 'Patient reports difficulty passing stools, requiring dietary or medical intervention.'],
            ['keyword' => 'Melaena', 'template' => 'Patient reports black, tarry stools, possibly indicative of gastrointestinal bleeding.'],
            ['keyword' => 'Bleeding PR', 'template' => 'Patient reports bleeding from the rectum, requiring further evaluation.'],
            ['keyword' => 'Mouth Ulcers', 'template' => 'Patient complains of painful mouth ulcers, possibly related to oral or systemic conditions.'],
            ['keyword' => 'Jaundice', 'template' => 'Patient presents with yellowing of the skin and eyes, possibly related to liver dysfunction.'],
            ['keyword' => 'Pale Stools', 'template' => 'Patient reports pale stools, possibly indicative of biliary obstruction.'],
            ['keyword' => 'Dark Urine', 'template' => 'Patient reports dark-colored urine, possibly related to liver or kidney issues.'],
            ['keyword' => 'Epigastric Pain', 'template' => 'Patient complains of pain in the epigastric region, possibly related to gastritis or peptic ulcer.'],
            ['keyword' => 'Groin Swelling', 'template' => 'Patient reports swelling in the groin area, possibly related to hernia or lymphadenopathy.'],
            ['keyword' => 'R/F Pain', 'template' => 'Patient reports pain in the right flank, possibly related to renal or musculoskeletal issues.'],
            ['keyword' => 'Loin Pain', 'template' => 'Patient complains of pain in the loin area, possibly related to renal issues.'],
            ['keyword' => 'Frequency Of Micturition', 'template' => 'Patient reports increased frequency of urination, possibly related to urinary tract infection or diabetes.'],
            ['keyword' => 'Urgency', 'template' => 'Patient reports a sudden, compelling urge to urinate, possibly related to urinary tract issues.'],
            ['keyword' => 'Dysuria', 'template' => 'Patient complains of painful urination, possibly related to urinary tract infection.'],
            ['keyword' => 'Polyuria', 'template' => 'Patient reports excessive urination, possibly related to diabetes or kidney issues.'],
            ['keyword' => 'Nocturia', 'template' => 'Patient reports waking up at night to urinate, possibly related to urinary or systemic conditions.'],
            ['keyword' => 'Hesitancy', 'template' => 'Patient reports difficulty initiating urination, possibly related to prostate or neurological issues.'],
            ['keyword' => 'Terminal Dribbling', 'template' => 'Patient reports dribbling of urine after voiding, possibly related to prostate issues.'],
            ['keyword' => 'Haematuria', 'template' => 'Patient reports blood in the urine, requiring further evaluation.'],
            ['keyword' => 'Urethral Discharge', 'template' => 'Patient reports discharge from the urethra, possibly related to infection.'],
            ['keyword' => 'Vaginal Discharge', 'template' => 'Patient reports abnormal vaginal discharge, possibly related to infection or hormonal changes.'],
            ['keyword' => 'Dyspareunia', 'template' => 'Patient complains of painful intercourse, possibly related to gynecological or psychological issues.'],
            ['keyword' => 'Menorrhagia', 'template' => 'Patient reports abnormally heavy menstrual bleeding, requiring further evaluation.'],
            ['keyword' => 'Metrorrhagia', 'template' => 'Patient reports irregular menstrual bleeding, possibly related to hormonal or uterine issues.'],
            ['keyword' => 'Pelvic Mass', 'template' => 'Patient reports a palpable mass in the pelvic region, requiring further investigation.'],
            ['keyword' => 'Lower Abdominal Pain', 'template' => 'Patient complains of pain in the lower abdomen, possibly related to gynecological or gastrointestinal issues.'],
            ['keyword' => 'Oligomenorrhea', 'template' => 'Patient reports infrequent menstrual periods, possibly related to hormonal imbalances.'],
            ['keyword' => 'Dysmenorrhea', 'template' => 'Patient complains of painful menstrual periods, possibly related to uterine or hormonal issues.'],
            ['keyword' => 'Enuresis', 'template' => 'Patient reports involuntary urination, especially at night, requiring further evaluation.'],
            ['keyword' => 'Urinary Incontinence', 'template' => 'Patient reports loss of bladder control, possibly related to neurological or muscular issues.'],
            ['keyword' => 'Numbness', 'template' => 'Patient reports numbness in [specific area], possibly related to neurological issues.'],
            ['keyword' => 'Depression', 'template' => 'Patient reports feelings of sadness and hopelessness, possibly related to depression.'],
            ['keyword' => 'Aggression', 'template' => 'Patient exhibits aggressive behavior, requiring psychological evaluation.'],
            ['keyword' => 'Flight of ideas', 'template' => 'Patient reports rapid, disjointed thoughts, possibly related to manic episodes.'],
            ['keyword' => 'Thought block', 'template' => 'Patient reports sudden interruption in thought processes, possibly related to psychiatric conditions.'],
            ['keyword' => 'Hallucinations', 'template' => 'Patient reports experiencing hallucinations, requiring psychiatric evaluation.'],
            ['keyword' => 'Delusions', 'template' => 'Patient reports fixed false beliefs, possibly related to psychiatric conditions.'],
            ['keyword' => 'Incoherent speech', 'template' => 'Patient exhibits incoherent speech, possibly related to neurological or psychiatric issues.'],
            ['keyword' => 'Pins and needles (paraesthesia)', 'template' => 'Patient reports tingling or prickling sensations, possibly related to nerve issues.'],
            ['keyword' => 'Weakness', 'template' => 'Patient reports generalized weakness, possibly related to systemic or neurological conditions.'],
            ['keyword' => 'Headache', 'template' => 'Patient complains of persistent headache, possibly related to tension or migraines.'],
            ['keyword' => 'Seizures/Fits/Convulsions', 'template' => 'Patient reports episodes of seizures, requiring neurological evaluation.'],
            ['keyword' => 'Fainting/Collapse', 'template' => 'Patient reports episodes of fainting or collapse, requiring further investigation.'],
            ['keyword' => 'Stool Incontinence', 'template' => 'Patient reports loss of bowel control, possibly related to neurological or gastrointestinal issues.'],
            ['keyword' => 'Dysarthria', 'template' => 'Patient reports difficulty speaking, possibly related to neurological issues.'],
            ['keyword' => 'Dysphasia', 'template' => 'Patient reports difficulty understanding or producing speech, possibly related to neurological issues.'],
            ['keyword' => 'Dysphonia', 'template' => 'Patient reports difficulty producing voice sounds, possibly related to laryngeal issues.'],
            ['keyword' => 'Unconsciousness', 'template' => 'Patient experienced a period of unconsciousness, requiring urgent evaluation.'],
            ['keyword' => 'Semi-conscious', 'template' => 'Patient is in a semi-conscious state, requiring urgent medical attention.'],
            ['keyword' => 'Stupor', 'template' => 'Patient is in a state of stupor, requiring urgent evaluation.'],
            ['keyword' => 'Confusion', 'template' => 'Patient reports confusion and disorientation, possibly related to neurological or systemic conditions.'],
            ['keyword' => 'Restlessness', 'template' => 'Patient exhibits restlessness, possibly related to anxiety or neurological issues.'],
            ['keyword' => 'Lethargy', 'template' => 'Patient reports extreme tiredness and lack of energy, possibly related to systemic conditions.'],
            ['keyword' => 'Aggressive behavior', 'template' => 'Patient exhibits aggressive behavior, requiring psychological evaluation.'],
            ['keyword' => 'Dyspraxia', 'template' => 'Patient reports difficulty coordinating movements, possibly related to neurological issues.'],
            ['keyword' => 'Neckache', 'template' => 'Patient complains of pain in the neck, possibly related to musculoskeletal issues.'],
            ['keyword' => 'Neck stiffness', 'template' => 'Patient reports stiffness in the neck, possibly related to musculoskeletal or neurological issues.'],
            ['keyword' => 'Joint pains', 'template' => 'Patient complains of pain in the joints, possibly related to arthritis or injury.'],
            ['keyword' => 'Joint Swelling', 'template' => 'Patient reports swelling in the joints, possibly related to arthritis or injury.'],
            ['keyword' => 'Morning stiffness of joints', 'template' => 'Patient reports stiffness in the joints upon waking, possibly related to arthritis.'],
            ['keyword' => 'General bodily pain', 'template' => 'Patient reports generalized pain throughout the body, possibly related to systemic conditions.'],
            ['keyword' => 'Backache', 'template' => 'Patient complains of pain in the back, possibly related to musculoskeletal issues.'],
            ['keyword' => 'Waist pain', 'template' => 'Patient reports pain in the waist area, possibly related to musculoskeletal or renal issues.'],
            ['keyword' => 'Low backache', 'template' => 'Patient complains of pain in the lower back, possibly related to musculoskeletal issues.'],
            ['keyword' => 'Painful thighs/legs', 'template' => 'Patient reports pain in the thighs or legs, possibly related to musculoskeletal or vascular issues.'],
            ['keyword' => 'Blindness', 'template' => 'Patient reports loss of vision, requiring urgent ophthalmological evaluation.'],
            ['keyword' => 'Double vision', 'template' => 'Patient reports seeing double, possibly related to neurological or ophthalmological issues.'],
            ['keyword' => 'Blurred vision', 'template' => 'Patient reports blurred vision, possibly related to refractive errors or systemic conditions.'],
            ['keyword' => 'Eye discharges', 'template' => 'Patient reports discharge from the eyes, possibly related to infection.'],
            ['keyword' => 'Excessive tearing', 'template' => 'Patient reports excessive tearing, possibly related to ophthalmological issues.'],
            ['keyword' => 'Itching eyes', 'template' => 'Patient reports itching in the eyes, possibly related to allergies or infection.'],
            ['keyword' => 'Reddened eyes or conjunctiva', 'template' => 'Patient reports redness in the eyes, possibly related to conjunctivitis or other conditions.'],
            ['keyword' => 'Foreign body in eyes', 'template' => 'Patient reports a foreign body sensation in the eyes, requiring urgent evaluation.'],
            ['keyword' => 'Periorbital swelling', 'template' => 'Patient reports swelling around the eyes, possibly related to infection or trauma.'],
            ['keyword' => 'Eyelid swelling', 'template' => 'Patient reports swelling of the eyelids, possibly related to infection or allergies.'],
            ['keyword' => 'Hearing loss (deafness)', 'template' => 'Patient reports loss of hearing, requiring audiological evaluation.'],
            ['keyword' => 'Tinnitus', 'template' => 'Patient reports ringing in the ears, possibly related to auditory or neurological issues.'],
            ['keyword' => 'Vertigo', 'template' => 'Patient reports dizziness and a sensation of spinning, possibly related to vestibular issues.'],
            ['keyword' => 'Earache', 'template' => 'Patient complains of pain in the ear, possibly related to infection or injury.'],
            ['keyword' => 'Pruritus oticus', 'template' => 'Patient reports itching in the ear, possibly related to infection or allergies.'],
            ['keyword' => 'Epistaxis', 'template' => 'Patient reports nosebleeds, requiring further evaluation.'],
            ['keyword' => 'Rhinorrhea', 'template' => 'Patient reports nasal discharge, possibly related to infection or allergies.'],
            ['keyword' => 'Foreign body in ear', 'template' => 'Patient reports a foreign body in the ear, requiring urgent evaluation.'],
            ['keyword' => 'Foreign body in nose', 'template' => 'Patient reports a foreign body in the nose, requiring urgent evaluation.'],
            ['keyword' => 'Halitosis', 'template' => 'Patient reports bad breath, possibly related to oral or systemic conditions.'],
            ['keyword' => 'Giddiness', 'template' => 'Patient reports a sensation of dizziness or lightheadedness, possibly related to vestibular or cardiovascular issues.'],
            ['keyword' => 'Arthralgia', 'template' => 'Patient reports joint pain, possibly related to arthritis or injury.'],
            ['keyword' => 'Chills', 'template' => 'Patient reports feeling cold and shivering, possibly related to infection.'],
            ['keyword' => 'Loss of Appetite', 'template' => 'Patient reports reduced appetite, possibly related to systemic or psychological conditions.'],
            ['keyword' => 'Bitter Taste', 'template' => 'Patient reports a persistent bitter taste in the mouth, possibly related to gastrointestinal or oral issues.'],
            ['keyword' => 'Warm to Touch', 'template' => 'Patient reports that the skin feels warm to touch, possibly related to infection or inflammation.'],
            ['keyword' => 'Heart Burns', 'template' => 'Patient reports a burning sensation in the chest, possibly related to acid reflux.'],
            ['keyword' => 'Cold', 'template' => 'Patient reports feeling cold, possibly related to environmental factors or systemic conditions.'],
            ['keyword' => 'Painful Left Shoulder', 'template' => 'Patient reports pain in the left shoulder, possibly related to musculoskeletal or referred pain.'],
            ['keyword' => 'Alcohol', 'template' => 'Patient reports excessive alcohol consumption, requiring further evaluation.'],
            ['keyword' => 'Burning Pain', 'template' => 'Patient reports a burning sensation, possibly related to nerve or tissue damage.'],
            ['keyword' => 'Stabbing Pain', 'template' => 'Patient reports sharp, stabbing pain, possibly related to nerve or tissue damage.'],
            ['keyword' => 'Lack of Sensation', 'template' => 'Patient reports numbness or lack of sensation, possibly related to neurological issues.'],
            ['keyword' => 'Itching Skin', 'template' => 'Patient reports itching of the skin, possibly related to dermatological or systemic conditions.'],
            ['keyword' => 'Vagina Itching', 'template' => 'Patient reports itching in the vaginal area, possibly related to infection or allergies.'],
            ['keyword' => 'Burning Sensation', 'template' => 'Patient reports a burning sensation, possibly related to nerve or tissue damage.'],
            ['keyword' => 'Clubbing', 'template' => 'Patient exhibits clubbing of the fingers, possibly related to chronic respiratory or cardiovascular conditions.'],
            ['keyword' => 'Koilonychia', 'template' => 'Patient reports spoon-shaped nails, possibly related to iron deficiency anemia.'],
            ['keyword' => 'Pale', 'template' => 'Patient appears pale, possibly related to anemia or systemic conditions.'],
            ['keyword' => 'Bleed Out', 'template' => 'Patient reports excessive bleeding, requiring urgent evaluation.'],
            ['keyword' => 'Stridor', 'template' => 'Patient reports a high-pitched breathing sound, possibly related to airway obstruction.'],
            ['keyword' => 'Peripheral Cyanosis', 'template' => 'Patient exhibits bluish discoloration of the extremities, possibly related to poor circulation.'],
            ['keyword' => 'Stiffness', 'template' => 'Patient reports stiffness in the muscles or joints, possibly related to musculoskeletal issues.'],
            ['keyword' => 'Bacterial Skin Infection', 'template' => 'Patient reports signs of bacterial skin infection, requiring treatment.'],
            ['keyword' => 'Tremor', 'template' => 'Patient reports involuntary shaking, possibly related to neurological or systemic conditions.'],
            ['keyword' => 'Fungal Skin Infection', 'template' => 'Patient reports signs of fungal skin infection, requiring treatment.'],
            ['keyword' => 'Swelling of Joint', 'template' => 'Patient reports swelling in the joints, possibly related to arthritis or injury.'],
            ['keyword' => 'Insomnia', 'template' => 'Patient reports difficulty sleeping, possibly related to psychological or environmental factors.'],
            ['keyword' => 'Easy Bleeding', 'template' => 'Patient reports easy bruising or bleeding, possibly related to hematological conditions.'],
            ['keyword' => 'Bruising', 'template' => 'Patient reports unexplained bruising, possibly related to hematological conditions.'],
            ['keyword' => 'Anemia', 'template' => 'Patient exhibits signs of anemia, requiring further evaluation.'],
            ['keyword' => 'New Skin Lesion', 'template' => 'Patient reports a new skin lesion, requiring dermatological evaluation.'],
            ['keyword' => 'Rash', 'template' => 'Patient reports a skin rash, possibly related to allergies or infection.'],
            ['keyword' => 'Breast Lump', 'template' => 'Patient reports a palpable lump in the breast, requiring further evaluation.'],
            ['keyword' => 'Nipple Discharge', 'template' => 'Patient reports discharge from the nipple, requiring further evaluation.'],
            ['keyword' => 'Cold', 'template' => 'Patient reports feeling cold, possibly related to environmental factors or systemic conditions.'],
            ['keyword' => 'Heat Intolerance', 'template' => 'Patient reports difficulty tolerating heat, possibly related to thyroid or systemic conditions.'],
            ['keyword' => 'Excessive Thirst', 'template' => 'Patient reports excessive thirst, possibly related to diabetes or other systemic conditions.'],
            ['keyword' => 'Throat Pain', 'template' => 'Patient reports pain in the throat, possibly related to infection or inflammation.'],
            ['keyword' => 'Otorrhoea', 'template' => 'Patient reports discharge from the ear, possibly related to infection.'],
            ['keyword' => 'Painful Swallowing', 'template' => 'Patient reports pain on swallowing, possibly related to throat or esophageal issues.'],
            ['keyword' => 'Chest Tightness', 'template' => 'Patient reports tightness or pressure in the chest, possibly related to cardiovascular issues.']
        ]);
    }
}
