INSERT INTO `service_points` (service_point_id, clinic_id,service_points, attendance_type_id, is_active, folder_prefix, folder_lenght, patient_type, gender_id, age_id, year_lenght, allow_capitation, queue_time_base_on) VALUES
	('SP01', 'C01', 'GENERAL', 'AT1', 'Yes', 'G', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP02', 'C09', 'GYNAE SCAN', 'AT9', 'No', 'A', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP03', 'C11', 'DENTAL', 'AT11', 'No', 'M', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP04', 'C07', 'EYE', 'AT7', 'Yes', 'E', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP05', 'C01', 'PHYSIOTHERAPY', 'AT1', 'No', 'F', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP06', 'C02', 'DIRECT SERVICE', 'AT2', 'No', 'D', '6', '2', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP07', 'C01', 'UROLOGY', 'AT1', 'No', 'B', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP08', 'C01', 'GENERAL SURGERY', 'AT1', 'Yes', 'X', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP09', 'C10', 'ENT', 'AT10', 'Yes', 'T', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP10', 'C01', 'PADIATERIC SURGERY', 'AT1', 'No', 'P', '6', '2', '1', '1', '2', 'No', 'SERVICE REQUEST'),
	('SP11', 'C12', 'ART', 'AT12', 'No', 'C', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP12', 'C12', 'SICKLE CELL', 'AT12', 'No', 'Q', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP13', 'C03', 'ANTENATAL', 'AT3', 'Yes', 'A', '6', '1', '3', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP14', 'C03', 'POSTNATAL', 'AT3', 'No', 'L', '6', '1', '3', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP15', 'C12', 'HERBAL', 'AT12', 'No', 'J', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP16', 'C01', 'PSYCHIATRY', 'AT1', 'No', 'O', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP17', 'C01', 'DIETETIC', 'AT1', 'Yes', 'Z', '6', '2', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP18', 'C12', 'DIABETIC', 'AT12', 'No', 'W', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP19', 'C08', 'PAED REFERAL', 'AT8', 'No', 'I', '6', '1', '1', '1', '2', 'No', 'SERVICE REQUEST'),
	('SP20', 'C01', 'ORTHOPAEDIC', 'AT1', 'No', 'Y', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP21', 'C01', 'PAEDIATRICS', 'AT1', 'No', 'H', '6', '1', '1', '1', '2', 'No', 'SERVICE REQUEST'),
	('SP22', 'C01', 'SPECIALIST CONSULTATION', 'AT1', 'Yes', 'S', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP23', 'C17', 'DIRECT PHARMACY', 'AT17', 'Yes', 'P', '6', '2', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP24', 'C01', 'HERBAL FAULTY', 'AT1', 'No', '', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST'),
	('SP25', 'C01', 'APPOINTMENT', 'AT19', 'No', 'K', '6', '1', '1', '3', '2', 'No', 'SERVICE REQUEST');